// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dmix_cpp
NumericVector dmix_cpp(NumericVector x, double d1, double s1, double d2, double s2, double w, bool log);
RcppExport SEXP _MATH4753S26CODY_dmix_cpp(SEXP xSEXP, SEXP d1SEXP, SEXP s1SEXP, SEXP d2SEXP, SEXP s2SEXP, SEXP wSEXP, SEXP logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< double >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< double >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< double >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    Rcpp::traits::input_parameter< bool >::type log(logSEXP);
    rcpp_result_gen = Rcpp::wrap(dmix_cpp(x, d1, s1, d2, s2, w, log));
    return rcpp_result_gen;
END_RCPP
}
// pmix_cpp
NumericVector pmix_cpp(NumericVector q, double d1, double s1, double d2, double s2, double w);
RcppExport SEXP _MATH4753S26CODY_pmix_cpp(SEXP qSEXP, SEXP d1SEXP, SEXP s1SEXP, SEXP d2SEXP, SEXP s2SEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type q(qSEXP);
    Rcpp::traits::input_parameter< double >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< double >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< double >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< double >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(pmix_cpp(q, d1, s1, d2, s2, w));
    return rcpp_result_gen;
END_RCPP
}
// rmix_cpp
NumericVector rmix_cpp(int n, double d1, double s1, double d2, double s2, double w);
RcppExport SEXP _MATH4753S26CODY_rmix_cpp(SEXP nSEXP, SEXP d1SEXP, SEXP s1SEXP, SEXP d2SEXP, SEXP s2SEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< double >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< double >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< double >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(rmix_cpp(n, d1, s1, d2, s2, w));
    return rcpp_result_gen;
END_RCPP
}
// qmix_cpp
NumericVector qmix_cpp(NumericVector p, double d1, double s1, double d2, double s2, double w);
RcppExport SEXP _MATH4753S26CODY_qmix_cpp(SEXP pSEXP, SEXP d1SEXP, SEXP s1SEXP, SEXP d2SEXP, SEXP s2SEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type d1(d1SEXP);
    Rcpp::traits::input_parameter< double >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< double >::type d2(d2SEXP);
    Rcpp::traits::input_parameter< double >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(qmix_cpp(p, d1, s1, d2, s2, w));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MATH4753S26CODY_dmix_cpp", (DL_FUNC) &_MATH4753S26CODY_dmix_cpp, 7},
    {"_MATH4753S26CODY_pmix_cpp", (DL_FUNC) &_MATH4753S26CODY_pmix_cpp, 6},
    {"_MATH4753S26CODY_rmix_cpp", (DL_FUNC) &_MATH4753S26CODY_rmix_cpp, 6},
    {"_MATH4753S26CODY_qmix_cpp", (DL_FUNC) &_MATH4753S26CODY_qmix_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_MATH4753S26CODY(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
