# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dmix_cpp <- function(x, d1, s1, d2, s2, w, log = FALSE) {
    .Call(`_MATH4753S26CODY_dmix_cpp`, x, d1, s1, d2, s2, w, log)
}

pmix_cpp <- function(q, d1, s1, d2, s2, w) {
    .Call(`_MATH4753S26CODY_pmix_cpp`, q, d1, s1, d2, s2, w)
}

rmix_cpp <- function(n, d1, s1, d2, s2, w) {
    .Call(`_MATH4753S26CODY_rmix_cpp`, n, d1, s1, d2, s2, w)
}

qmix_cpp <- function(p, d1, s1, d2, s2, w) {
    .Call(`_MATH4753S26CODY_qmix_cpp`, p, d1, s1, d2, s2, w)
}

